- src/main.go
In some cases hasUnrecognizedKeys can apparently be handed a pointer to
a struct, as opposed to just a struct. This commit checks if refType is
a pointer, and dereferences it if it is.
> hasUnrecognizedKeys failed to dereference pointer

- doc/configuration.md
Fixes an invalid key in the specification document.
> Specification: Replace remote file "source" key with "url"

- internal/main.go
The in-file and out-file logic failed to assign the opened/created file
pointers to the local variables, resulting in these flags being broken.
This commit fixes that.
> internal/main: in-file and out-file flags were broken

- Dockerfile.build-exec
- Dockerfile.build-image
- build-docker
Usage:
docker run -i --rm coreos/ct <ignition.yaml >ignition.json
> build-docker creates a scratch Docker image

- internal/main.go
When invoked with this flag, ct will fail unless there are no errors,
warnings, deprecations, etc..
> main: add strict flag

- config/types/common.go
- config/types/etcd.go
- config/types/flannel.go
(This PR is based on https://github.com/coreos/container-linux-config-transpiler/pull/36, so ignore all but the final commit. Will rebase once that PR is merged)
This commit refactors the etcd and flannel logic to pass the arguments to the service via the command line instead of environment variables. This is necessary for the coreos-metadata templating logic in a following commit.
> config/{etcd,flannel}: pass options via command line instead of env vars

- config/types/config.go
- config/types/update.go
- config/types/update_test.go
(This PR is based on #36, so ignore all but the final commit. Will rebase once that PR is merged)
This commit lets users configure the update group and server for a machine:
```
update:
channel: beta
server: https://public.update.core-os.net/v1/update/
```
A resulting ignition config is viewable here (ignore the strategy bit): https://gist.github.com/dgonyeo/9f98a88353dbae078c66eb9487206919
There was no documentation on this config file that I could find, so someone should sanity check it for me.
Fixes https://github.com/coreos/bugs/issues/1861.
This new feature needs documentation, waiting on https://github.com/coreos/container-linux-config-transpiler/pull/37 to be merged before I write it.
>  config/types/update: can now configure update group and server

- config/config.go
- config/config_test.go
- config/templating/templating.go
- config/templating/templating_test.go
- config/types/common.go
- config/types/config.go
- config/types/converter.go
- config/types/disks.go
- config/types/etcd.go
- config/types/files.go
- config/types/filesystems.go
- config/types/flannel.go
- config/types/networkd.go
- config/types/passwd.go
- config/types/raid.go
- config/types/systemd.go
- config/types/update.go
- internal/main.go
(This PR is based on https://github.com/coreos/container-linux-config-transpiler/pull/38, so ignore all but the final commit. Will rebase once that PR is merged)
Users can now use `{}` to refer to dynamic information (like public ipv4
address) that will be filled in via an environment variable populated by
the coreos metadata service (which is also enabled and added as a
requirement if templating is used).
This is notably only usable inside the etcd and flannel sections. I could enable it in other places like systemd units, if we think it wouldn't be too confusing.
This commit also needs documentation to be written for it, but I'm holding off on doing that until https://github.com/coreos/container-linux-config-transpiler/pull/37 gets merged.
Example usage: …
> config: templating implemented for etcd and flannel sections

- config/types/config.go
- config/types/docker.go
Allows configs to specify docker flags such as:
```yaml
docker:
flags:
- --config-file
- /etc/docker/daemon.json
- --default-gateway
- 172.16.0.1
```
This is converted into a drop-in specifying the DOCKER_OPTS environment
variable for docker.service.
Fixes https://github.com/coreos/bugs/issues/1851
This needs to be documented, waiting on https://github.com/coreos/container-linux-config-transpiler/pull/37 to be merged before doing so.
> config: add docker sugar

- config/types/config.go
- config/types/locksmith.go
- config/types/update.go
- doc/configuration.md
Mostly a continuation of https://github.com/coreos/container-linux-config-transpiler/pull/40
Waiting on https://github.com/coreos/container-linux-config-transpiler/pull/37 to be merged before I write the docs
> config/types/locksmith: added configuration for locksmith reboot strat

- config/templating/templating.go
- doc/dynamic-data.md
Because the openstack-metadata support in coreos-metadata was in progress when I initially wrote the templating logic in ct, I forgot to include support for it.
This commit adds in support for using coreos-metadata with the openstack metadata service for dynamic data in CLCs.
This commit also flips the rows and columns in the dynamic data support table in the docs, so it's easier to grow (and adds openstack-metadata).
> config/templating: added support for dynamic data in openstack-metadata

- config/types/locksmith.go
- doc/configuration.md
This entire project uses underscores in yaml key names, the recent
locksmith commit broke this pattern by using a hyphen. This commit fixes
the mistake.
> config/types/locksmith: replace hyphen with underscore

- NEWS
28-Mar-2016 CONFIG-TRANSPILER v0.2.1
- Added platform support for openstack-metadata
- reboot-strategy under the locksmith section renamed to reboot_strategy to
be consistent with the rest of the schema
> news: add news for v0.2.1

- internal/main.go
Without this change, two newlines are emitted on stderr, which offsets
the output of ct when run in a terminal.
> main: only print reports if there are entries

- config/config_test.go
- config/types/etcd.go
- config/types/flannel.go
- doc/configuration.md
This commit makes the version field in the etcd and flannel sections not
required. If the field is left empty, default versions are assumed
for the purposes of parsing and validating the passed options. For etcd,
v3.0 is assumed and for flannel, v0.6 is assumed.
Fixes https://github.com/coreos/bugs/issues/1894
> config/types/{etcd,flannel}: make version field not required

- NEWS
Also fixes timestamps for v0.2.0 and v0.2.1
This release is necessary for the docs in https://github.com/coreos/docs/pull/1024 to be correct.
> news: add news for v0.2.2

- config/types/common.go
- config/types/locksmith.go
- config/types/locksmith_test.go
- config/types/update.go
- doc/configuration.md
- doc/examples.md
This commit allows users to configure all fields available in locksmithd, including things like reboot windows and etcd endpoints.
Fixes https://github.com/coreos/bugs/issues/1884.
> config/types/locksmith: add missing fields

- internal/main.go
If conversion fails, the report is printed and the program is exited.
Before this commit the string "Generated Ignition config was invalid."
was printed to stderr, which is unnecessary since the report was already
printed.
> internal: remove "generated ignition config is invalid" line

- config/config.go
Doing this because @dghubble was confused about an added argument to `ConvertAs2_0`, and if these comments are in place I'll remember to update them if fields are added in the future.
> config/config.go: add comments for the exported functions

- Makefile
- test
`ct` release binaries are dynamically linked and don't work in various containers (e.g. scratch, alpine). Let's define a Makefile to formalize the build process so its not as dependent on whatever env vars the release engineer happens to have set. Notably, set CGO_ENABLED to 0.
I've left the old atypical build script which does symlinking, pending comment.
> Add Makefile to build static bin/ct binary

- .travis.yml
I think we mean to be supporting and testing against recent Go versions. Leave Go 1.5 or drop?
> travis.yml: Add test coverage for Go 1.7 and 1.8

- config/types/common.go
boolean, integer values are broken in %q
We are getting
```
key, val: auto-compaction-retention '\x01'
key, val: debug %!q(bool=true)
```
since the default format string `"--%s=%q"`.
If there's any better way to handle this, please feel free to close this :)
Thanks!
> config/types: use %q for 'string' values

- config/templating/templating.go
In the gce provider the public and private variable names were
backwards. This commit fixes that.
> config/templating: swap v4 public and private variables for gce

- doc/dynamic-data.md
- doc/examples.md
The `advertise_client_urls` and `initial_advertise_peer_urls` fields in
the etcd section must include url schema prefixes in their values (e.g.
http://). This commit updates doc/dynamic-data.md and doc/examples.md to
add these to the examples.
Fixes https://github.com/coreos/bugs/issues/1952
> doc: fix broken etcd examples

- config/types/common.go
- config/types/etcd.go
- config/types/flannel.go
- config/types/util/unit.go
- config/types/util/unit_test.go
- doc/configuration.md
This commit adds a new field to flannel called network-config. When
contents are provided to it, an `ExecStartPre` is added to the produced
flannel unit that will call `etcdctl` to set flannel's config to the
endpoint that flannel is configured to use.
As an example the following config:
```yaml
flannel:
version: 0.7.0
network_config: |-
{ "Network": "10.1.0.0/16" }
interface: "{PUBLIC_IPV4}"
etcd_endpoints: "https://127.0.0.1:2379"
etcd_cafile: "/etc/ssl/etcd/ca.pem"
etcd_certfile: "/etc/ssl/etcd/cert.pem"
etcd_keyfile: "/etc/ssl/etcd/key.pem"
```
Generates this unit:
```
[Unit]
Requires=coreos-metadata.service
After=coreos-metadata.service
[Service]
EnvironmentFile=/run/metadata/coreos
Environment="FLANNEL_IMAGE_TAG=v0.7.0"
ExecStart=
ExecStart=/usr/lib/coreos/flannel-wrapper …
```
> config/types/flannel: added network-config option

- .gitignore
- Makefile
- git-version
I noticed the v0.3.1 release is still dynamically linked and was build with the build script. Could we formalize the Makefile build/release?
Run `make release` at a release tag (say v0.3.2) to produce:
```
ls _output
ct-v0.3.2-x86_64-apple-darwin 
ct-v0.3.2-x86_64-pc-windows-gnu
ct-v0.3.2-x86_64-unknown-linux-gnu
```
I've matched the existing names (unknown-linux-gnu, apple-darwin, pc-windows-gnu), though they seem odd. Is there a reason for those? Maybe just linux, darwin, windows? cc @crawford
> Makefile: Add release target to produce static binaries

- doc/examples.md
This commit changes the password hashes in the examples to be in quotes
and to look more like an actual password hash. This will hopefully
reduce user confusion around this field.
Fixes https://github.com/coreos/bugs/issues/1955
> doc/examples.md: make example password hashes clearer

- internal/main.go
When the strict flag was originally introduced, it didn't take into
account the fact that the conversion function can return non-fatal
reports. This corrects that mistake by failing when there are any
reports that are returned.
> main: expand strict coverage

- doc/configuration.md
The size and start of a partition should be expressed with SI units
(e.g. MB, GB), not as a raw number of sectors.
> docs: fix specification for partitions

- README.md
README.md: updated version number in --branch to most recent under compile from source
I compiled ct from source following the instructions in README.md and had issues with transpiling my config.  I opened an issue and after some research identified that I had pulled branch v0.1.0 instead of the most recent one.  To prevent other people from making this same mistake and to close out the issue I opened, I created this pull request with updated version and a note for current releases.  
Issue:  https://github.com/coreos/bugs/issues/1991
> Update Readme.md for latest version to build from source

- config/types/locksmith.go
The envvar generated by ct is called LOCKSMITHD_ENDPOINTS, but the real var honoured by Locksmith is LOCKSMITHD_ENDPOINT (in the singular).
> locksmith: fix envvar name LOCKSMITHD_ENDPOINT

- doc/configuration.md
Typo: `typeguid_` -> `type_guid`
Types:
start and size of partition is either "0" (integer) or some SI-unit ( e.g. "512B", "4KB", or "512GiB"), see: https://github.com/alecthomas/units/blob/master/bytes.go.
> Fixed a little typo and wrong types.

- doc/configuration.md
https://github.com/coreos/container-linux-config-transpiler/commit/a6854106afad1c7b10848e22fd2226547e13f96c added the **network_config** option to the Flannel code. But the updated documentation called it **flannel_config** instead.
> network_config incorrectly documented

- config/types/common.go
coreos-metadata-sshkey@.service's provider should be overridden on the
openstack-metadata platform. This commit makes that change.
> config/types: override sshkeys's opts on openstack-metadata

- config/types/flannel.go
Previously, if the version was not specified, the version was
printed as v\u003cnil\u003e in the outputted ignition file.
This fixes that.
> config/types/flannel: allow empty version field

- config/templating/templating.go
- doc/dynamic-data.md
This adds support for the vagrant-virtualbox provider, added in coreos-metadata version 0.11.0
> templating: add vagrant-virtualbox provider

- doc/dynamic-data.md
- doc/examples.md
This resolves an issue where the example provided causes etcd-member to fail the startup process.
```
Jul 18 15:47:56 core-01 etcd-wrapper[1027]: 2017-07-18 15:47:56.788293 C | etcdmain: couldn't find local name "$HOSTNAME" in the initial cluster configuration
```
Refs https://github.com/coreos/bugs/issues/2054
- Tested on `vagrant-virtualbox`
> docs: Fix naming mismatch causing etcd failure.

- config/config.go
- config/platform/platform.go
- config/templating/templating.go
- config/types/common.go
- internal/main.go
Before this PR ct only checked if the platform was valid when templating was used. While this probably should have been checked in every situation from the start, with the addition of [overriding coreos-metadata's platform when the openstack-metadata platform is used](https://github.com/coreos/container-linux-config-transpiler/commit/d273220f53c727aca507d254828460404f329eeb), there were now situations where the platform is relevant outside of templating.
Fixes https://github.com/coreos/bugs/issues/2075
> Check platform

- config/config_test.go
- config/types/passwd.go
Fixes https://github.com/coreos/bugs/issues/2003
> config/types/passwd: always emit create for non-core users

- glide.lock
- glide.yaml
- vendor/github.com/coreos/ignition/config/types/config.go
- vendor/github.com/coreos/ignition/config/types/schema.go
- vendor/github.com/coreos/ignition/config/types/url.go
We'd like to update ct within matchbox since it hasn't been updated in a while https://github.com/coreos/matchbox/issues/606. Using Ignition v0.17.2 seems like a good place to make the cut.
> glide.yaml: vendor ignition v0.17.2

- config/types/locksmith.go
- config/types/locksmith_test.go
Change validation logic in the locksmith struct to attach all validation
functions to the top level locksmith struct, such that the string
special casing in config/types/common.go#getArgs can be relied on to
quote escape the strings, and %s can be used in the provided format
string instead of %q.
This bug was introduced in https://github.com/coreos/container-linux-config-transpiler/pull/66. It only affects the locksmith section because the format string the locksmith section provides to `getArgs` was `%q` to handle spaces before the PR that introduced the bug, and I believe that I didn't notice this bug when reviewing that PR because some of the fields in the `Locksmith` struct were type aliased so that validation functions could be attached, and thus failed the string special casing …
> config/types/locksmith: don't use custom types to validate fields

- doc/configuration.md
Reword documentation of passwd.users to be declaritive not imperitive.
Fixes https://github.com/coreos/bugs/issues/1967
I left the `passwd.groups` alone because
1) Ignition's docs are written that way
2) Ignition's docs are correct. We do not do the checking we do with users and instead call `groupadd` with no checks for existing groups, thus it really is a list of "groups to create". This is probably not ideal (unless there's some explicit reason we do it this way), but we should fix the behavior before the docs.
> docs: fix passwd.users wording to match 2.1.0 spec

- config/types/common.go
when an openstack provider is specified to ct, a dropin is created to
override the provider value when coreos-metadata is run. this is because
there is no "openstack" provider, since there are two possible metadata
sources and we can't rely on either existing or discover which to use,
so it must be specified for us explicitly.
however, the dropin that was created failed to enable the ssh-keys
service. this would normally be done by ignition for providers where we
can retrieve ssh keys, but since openstack keys are only available if we
know which metadata service to use, we have to enable it in the dropin
instead of enabling it across the board for the openstack provider.
ref coreos/bugs#2247
> config: enable coreos-metadata-sshkeys serice on openstack

- doc/examples.md
the docs have an example that modifies the shell to /bin/zsh, but
container linux doesn't have /bin/zsh installed, and probably never
will. this updates the example to work on actual machines.
fixes coreos/bugs#2274
> doc: use /bin/bash in shell example

- config/types/files.go
The report was created, but never merged, so it would not be presented to the user in the case of an error.
> Actually report remote url errors in remote file config

- doc/examples.md
`mkpasswd` can be used to generate password hashes, so this updates the
password_hash example to instruct users to use `mkpasswd`.
This change comes from the discussion in https://github.com/coreos/bugs/issues/1954
> doc/example: add mkpasswd instructions to password_hash example

- doc/configuration.md
follow the pattern of colons after the property name
> readme: add missing colons after property name

- README.md
the branch previously specified (v0.3.1) doesn't seem to exist.
UPDATE: `v0.3.1` was actually based on a tag that I didn't see but happened to be outdated, `v0.5.0` is the latest one, so a new commit was made to reflect that.
> readme: update git clone --branch from v0.3.1 to v0.5.0

- config/types/files.go
- doc/configuration.md
- internal/main.go
This adds one more file contents source, `local`, in addition to `inline` and `remote`. It takes a filename, and includes the contents of that file. This is useful when you don’t want to pollute the ign file with many large inline files, or when you don’t want to indent the contents of the file to fit the yaml syntax. Also, editing such a local config file is easier when it is a separate file, because an editor can enable format-specific features.
Local files are expected to be in the same directory as the ign file, so you could track both under source control; this is just for convenience.
Currently this uses the path as is, so local paths are interpreted relative to the working directory. It would be nice to have them relative to the ign file, so the output does not depend on where `ct` …
> Add support for local files

- internal/main.go
Don't open the output file/stream until after conversion is done. This prevents writing empty files when ct fails.
> main: dont open output before conversion

- config/config_test.go
- config/types/files.go
When the mode for a file or directory is unset in a CLC, default them to
0644 and 0755 respectively, and emit a warning.
Based on a pre-holiday conversation with @ajeddeloh and @bgilbert
> config/types: default unset modes to sensible values

- config/platform/platform.go
- config/templating/templating.go
- doc/dynamic-data.md
Add the ability to bring your own metadata service. Add a "custom" platform type and document how to use it by overwriting parts of the coreos-metadata service
> Support custom platforms

- doc/dynamic-data.md
The docs builder doesn't have the newest ct version. Change the CLCs in
the docs to just be yaml until the docs builder has ct 0.7.0.
> doc/dynamic-data: use platforms in dyn. data docs 

- doc/examples.md
Pulls in block of ways to generate password hashes from [cloudinit's
documentation][1].
[1]: https://github.com/coreos/coreos-cloudinit/blame/master/Documentation/cloud-config.md#L415-L434
> doc/example.md: include more methods to generate password hashes

- config/types/files.go
ct should error on a config when a users sets more than one source for a file. Setting no source results in an empty file being created, which seems fine to me.
> config: emit error when more than one source is set for a file

- Makefile
Prior to this, running 'make', changing go files, and running 'make'
again failed to rebuild 'bin/ct' since the file already exists and was
not a phony target (even though 'all' was).
This fixes that issue by correctly modeling the go files it depends on
> make: fix bin/ct target dependencies

- config/config_test.go
- config/types/common.go
- config/types/etcd.go
Also adds a test to ensure the flag for etcd is set to false.
Fixes https://github.com/coreos/bugs/issues/2428
We should definitely do a full audit of options, I wouldn't be surprised if there are other fields with this issue. Until we do though, this will at least fix the reported issue.
> config: make getCliArgs handle pointers, make etcd.EnableV2 a pointer

- doc/overview.md
This missing link was what I struggled most with, when I started using CoreOS.
> docs/overview: link to the config-transpiler repository

- config/types/files.go
Do not warn if there is no mode and you are appending.
> config/types/files: dont' warn on no mode w/append

- config/types/files.go
Report that a default mode will be used for files which do not exist
with level "info".
> config/types/files: Report default mode for files

- config/types/config.go
Add version field. Only allow 0 or unspecified. This starts versioning
the spec in a backwards compatible way.
> types/config: add version field

- README.md
Add a note that this tool is for Container Linux and direct Fedora
CoreOS users to FCCT.
> readme: add note about fcct
